import { generateNode } from '@/lib/ai'
import { prisma } from '@/lib/db'
import { isDomainId, DEFAULT_DOMAIN } from '@/lib/domains'

// Sentinel for the lost-race case in the expand transaction. Thrown inside
// the prisma.$transaction callback so the entire transaction rolls back,
// then caught by the outer handler to return 409.
class StubAlreadyGenerated extends Error {}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const sessionId = searchParams.get('sessionId')

  if (!sessionId) {
    return Response.json({ error: 'sessionId is required' }, { status: 400 })
  }

  try {
    const [nodes, session] = await Promise.all([
      prisma.node.findMany({
        where: { sessionId },
        // Siblings share createdAt to ms precision (one createMany), so ordinal
        // carries the planner's foundational→advanced order across refreshes;
        // id is a final stable tiebreaker.
        orderBy: [{ createdAt: 'asc' }, { ordinal: 'asc' }, { id: 'asc' }],
      }),
      prisma.session.findUnique({
        where: { id: sessionId },
        select: { domain: true, topic: true },
      }),
    ])
    if (nodes.length === 0 || !session) {
      return Response.json({ error: 'Session not found' }, { status: 404 })
    }
    const domain = isDomainId(session.domain) ? session.domain : DEFAULT_DOMAIN
    return Response.json({ data: { nodes, domain, topic: session.topic } })
  } catch (err) {
    console.error('loadSession failed:', err)
    const message = err instanceof Error ? err.message : 'Failed to load session'
    return Response.json({ error: message }, { status: 500 })
  }
}

export async function POST(request: Request) {
  let body: unknown
  try {
    body = await request.json()
  } catch {
    return Response.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const b = typeof body === 'object' && body !== null ? (body as Record<string, unknown>) : {}
  const nodeId = typeof b.nodeId === 'string' ? b.nodeId : ''
  const rawDomain = typeof b.domain === 'string' ? b.domain : DEFAULT_DOMAIN
  const domain = isDomainId(rawDomain) ? rawDomain : DEFAULT_DOMAIN

  if (!nodeId) {
    return Response.json({ error: 'nodeId is required' }, { status: 400 })
  }

  try {
    const target = await prisma.node.findUnique({ where: { id: nodeId } })
    if (!target) {
      return Response.json({ error: 'Node not found' }, { status: 404 })
    }
    if (target.status !== 'stub') {
      return Response.json({ error: 'Node is already generated' }, { status: 400 })
    }

    const ancestorPath = await buildAncestorPath(nodeId, target.sessionId)
    const data = await generateNode(target.title, ancestorPath, domain)

    // Wrap the stub→generated update, child stub creation, and child reload
    // in a single transaction so a half-expanded state can never escape:
    // either both writes land or neither does, and the post-update read
    // sees its own writes.
    const result = await prisma.$transaction(async tx => {
      let updatedNode
      try {
        updatedNode = await tx.node.update({
          where: { id: nodeId, status: 'stub' },
          data: {
            description: data.description,
            hasDiagram: data.needsDiagram,
            status: 'generated',
          },
        })
      } catch (err) {
        if (err instanceof Error && 'code' in err && (err as { code: string }).code === 'P2025') {
          throw new StubAlreadyGenerated()
        }
        throw err
      }

      if (data.needsDiagram && data.children.length > 0) {
        await tx.node.createMany({
          data: data.children.map((title, index) => ({
            sessionId: target.sessionId,
            parentId: nodeId,
            title,
            description: null,
            hasDiagram: false,
            status: 'stub',
            ordinal: index,
          })),
        })
      }

      const children = await tx.node.findMany({
        where: { sessionId: target.sessionId, parentId: nodeId },
        orderBy: [{ createdAt: 'asc' }, { ordinal: 'asc' }, { id: 'asc' }],
      })

      return { node: updatedNode, children }
    })

    return Response.json({ data: result })
  } catch (err) {
    if (err instanceof StubAlreadyGenerated) {
      return Response.json({ error: 'Node was already generated by another request' }, { status: 409 })
    }
    console.error('expandNode failed:', err)
    const message = err instanceof Error ? err.message : 'Expansion failed'
    return Response.json({ error: message }, { status: 500 })
  }
}

async function buildAncestorPath(nodeId: string, sessionId: string): Promise<string> {
  const allNodes = await prisma.node.findMany({
    where: { sessionId },
    select: { id: true, title: true, parentId: true },
  })

  const nodeMap = new Map(allNodes.map(n => [n.id, n]))
  const path: string[] = []
  let current = nodeMap.get(nodeId)
  while (current) {
    path.unshift(current.title)
    current = current.parentId ? nodeMap.get(current.parentId) : undefined
  }

  return path.join(' > ')
}
