import { generateNode } from '@/lib/ai'
import { prisma } from '@/lib/db'

// Sentinel for the lost-race case in the expand transaction. Thrown inside
// the prisma.$transaction callback so the entire transaction rolls back,
// then caught by the outer handler to return 409.
class StubAlreadyGenerated extends Error {}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const sessionId = searchParams.get('sessionId')

  if (!sessionId) {
    return Response.json({ error: 'sessionId is required' }, { status: 400 })
  }

  try {
    const nodes = await prisma.node.findMany({
      where: { sessionId },
      // Stub siblings are written in a single createMany and end up with
      // identical createdAt to ms precision. Adding id as a tiebreaker keeps
      // the canvas layout stable across refreshes.
      orderBy: [{ createdAt: 'asc' }, { id: 'asc' }],
    })
    if (nodes.length === 0) {
      return Response.json({ error: 'Session not found' }, { status: 404 })
    }
    return Response.json({ data: nodes })
  } catch (err) {
    console.error('loadSession failed:', err)
    const message = err instanceof Error ? err.message : 'Failed to load session'
    return Response.json({ error: message }, { status: 500 })
  }
}

export async function POST(request: Request) {
  let body: unknown
  try {
    body = await request.json()
  } catch {
    return Response.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const nodeId =
    typeof body === 'object' && body !== null && typeof (body as { nodeId?: unknown }).nodeId === 'string'
      ? (body as { nodeId: string }).nodeId
      : ''

  if (!nodeId) {
    return Response.json({ error: 'nodeId is required' }, { status: 400 })
  }

  try {
    const target = await prisma.node.findUnique({ where: { id: nodeId } })
    if (!target) {
      return Response.json({ error: 'Node not found' }, { status: 404 })
    }
    if (target.status !== 'stub') {
      return Response.json({ error: 'Node is already generated' }, { status: 400 })
    }

    const ancestorPath = await buildAncestorPath(nodeId, target.sessionId)
    const data = await generateNode(target.title, ancestorPath)

    // Wrap the stub→generated update, child stub creation, and child reload
    // in a single transaction so a half-expanded state can never escape:
    // either both writes land or neither does, and the post-update read
    // sees its own writes.
    const result = await prisma.$transaction(async tx => {
      let updatedNode
      try {
        updatedNode = await tx.node.update({
          where: { id: nodeId, status: 'stub' },
          data: {
            description: data.description,
            hasDiagram: data.needsDiagram,
            status: 'generated',
          },
        })
      } catch (err) {
        if (err instanceof Error && 'code' in err && (err as { code: string }).code === 'P2025') {
          throw new StubAlreadyGenerated()
        }
        throw err
      }

      if (data.needsDiagram && data.children.length > 0) {
        await tx.node.createMany({
          data: data.children.map(title => ({
            sessionId: target.sessionId,
            parentId: nodeId,
            title,
            description: null,
            hasDiagram: false,
            status: 'stub',
          })),
        })
      }

      const children = await tx.node.findMany({
        where: { sessionId: target.sessionId, parentId: nodeId },
        orderBy: [{ createdAt: 'asc' }, { id: 'asc' }],
      })

      return { node: updatedNode, children }
    })

    return Response.json({ data: result })
  } catch (err) {
    if (err instanceof StubAlreadyGenerated) {
      return Response.json({ error: 'Node was already generated by another request' }, { status: 409 })
    }
    console.error('expandNode failed:', err)
    const message = err instanceof Error ? err.message : 'Expansion failed'
    return Response.json({ error: message }, { status: 500 })
  }
}

async function buildAncestorPath(nodeId: string, sessionId: string): Promise<string> {
  const allNodes = await prisma.node.findMany({
    where: { sessionId },
    select: { id: true, title: true, parentId: true },
  })

  const nodeMap = new Map(allNodes.map(n => [n.id, n]))
  const path: string[] = []
  let current = nodeMap.get(nodeId)
  while (current) {
    path.unshift(current.title)
    current = current.parentId ? nodeMap.get(current.parentId) : undefined
  }

  return path.join(' > ')
}
